name: godot-4
base: core24
version: 4.5-stable
summary: The game engine you've been waiting for.
description: |
  The Godot Engine is a free, all-in-one, cross-platform game engine that makes it easy for you to create 2D and 3D games.

grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

compression: lzo

layout:
  /usr/lib/dotnet:
    bind: $SNAP/usr/lib/dotnet
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri
  /usr/share/vulkan:
    bind: $SNAP/usr/share/vulkan
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libvulkan_intel.so:
    bind-file: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libvulkan_intel.so
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libvulkan_lvp.so:
    bind-file: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libvulkan_lvp.so
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libvulkan_radeon.so:
    bind-file: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libvulkan_radeon.so
  /usr/lib/git-core:
    bind: $SNAP/usr/lib/git-core
  /usr/share/git-core:
    bind: $SNAP/usr/share/git-core
  /etc/gitconfig:
    bind-file: $SNAP/etc/gitconfig

parts:
  dotnet:
    plugin: nil
    stage-packages:
      - dotnet-sdk-8.0
      - dotnet-runtime-8.0
      - dotnet8
      - dotnet-host

    prime:
      - usr/bin/dotnet
      - usr/lib/dotnet
      - usr/lib/*/liblttng-ust*
      - usr/lib/*/libnuma*

  libs:
    plugin: nil
    stage-packages:
      - libspeechd2
      - mesa-va-drivers
      - mesa-vulkan-drivers
      - vulkan-tools
    prime:
      - usr/lib/*/libspeech*
      - usr/lib/*/dri
      - usr/lib/*/libVk*
      - usr/lib/*/libvulkan*
      - usr/lib/*/libxcb-randr*
      - usr/share/vulkan
      - usr/bin/vk*

  godot-4:
    plugin: nil
    build-packages:
      - curl
      - unzip
    override-build: |
      set -ex
      case "$CRAFT_ARCH_BUILD_FOR" in
        amd64)  arch=x86_64    ;;
        arm64)  arch=arm64  ;;
        *)      arch=""     ;;
      esac

      rm -rf $CRAFT_PART_INSTALL/*

      if [[ -n $arch ]]; then
        curl -LO --retry-connrefused --retry 10 https://github.com/godotengine/godot/releases/download/$SNAPCRAFT_PROJECT_VERSION-stable/Godot_v$SNAPCRAFT_PROJECT_VERSION-stable_mono_linux_$arch.zip
      else
        echo "Unsupported arch"
        exit 1
      fi

      unzip *zip
      rm -f *zip
      mkdir tmp
      mv Godot*/* $CRAFT_PART_INSTALL/
      mv $CRAFT_PART_INSTALL/Godot_v$SNAPCRAFT_PROJECT_VERSION-stable_mono_linux.* $CRAFT_PART_INSTALL/godot-4

  git:
    plugin: nil
    stage-packages:
      - git
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/etc
      touch $CRAFT_PART_INSTALL/etc/gitconfig
    prime:
      - -usr/share/doc
      - -etc/bash*

  desktop-file:
    plugin: dump
    source: desktop-file
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp * $CRAFT_PART_INSTALL/meta/gui

  cleanup:
    after: [ godot-4 ]
    plugin: nil
    build-snaps: [ gnome-46-2404 ]
    override-prime: |
        set -eux
        cd /snap/gnome-46-2404/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;

apps:
  godot-4:
    extensions: [gnome]
    command: godot-4
    desktop: meta/gui/godot-4.desktop
    plugs:
      - home
      - network
      - audio-playback
      - audio-record
      - removable-media
      - joystick
      - hardware-observe
    environment:
      HOME: $SNAP_USER_COMMON
      VK_ICD_FILENAMESr: /var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:$SNAP/usr/share/vulkan/icd.d/intel_icd.x86_64.json
