name: godot-3-5
base: core22
version: 3.5.1
summary: The game engine you've been waiting for.
description: |
  The Godot Engine is a free, all-in-one, cross-platform game engine that makes it easy for you to create 2D and 3D games.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
compression: lzo

layout:
  /usr/lib/dotnet:
    bind: $SNAP/usr/lib/dotnet
  /usr/share/drirc.d:
    bind: $SNAP/usr/share/drirc.d
  /usr/lib/x86_64-linux-gnu/dri:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/dri
  /usr/share/vulkan:
    bind: $SNAP/usr/share/vulkan
  /usr/lib/x86_64-linux-gnu/libvulkan_intel.so:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libvulkan_intel.so
  /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
  /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so:
    bind-file: $SNAP/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so

parts:
  dotnet:
    plugin: nil
    stage-packages:
      - dotnet-sdk-6.0
      - dotnet-runtime-6.0
      - dotnet6
      - dotnet-host

    prime:
      - usr/bin/dotnet
      - usr/lib/dotnet
      - usr/lib/*/liblttng-ust*
      - usr/lib/*/libnuma*

  libs:
    plugin: nil
    stage-packages:
      - mesa-va-drivers
      - mesa-vulkan-drivers
      - vulkan-tools
    prime:
      - usr/lib/*/dri
      - usr/lib/*/libVk*
      - usr/lib/*/libvulkan*
      - usr/lib/*/libxcb-randr*
      - usr/share/vulkan
      - usr/bin/vk*

  godot-3-5:
    plugin: dump
    source: https://downloads.tuxfamily.org/godotengine/$SNAPCRAFT_PROJECT_VERSION/mono/Godot_v$SNAPCRAFT_PROJECT_VERSION-stable_mono_x11_64.zip
    override-build: |
      craftctl default
      mv Godot* tmp/
      mv tmp/* $CRAFT_PART_INSTALL/
      rmdir tmp

  desktop-file:
    plugin: dump
    source: desktop-file
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp * $CRAFT_PART_INSTALL/meta/gui

  cleanup:
    after: [ godot-3-5 ]
    plugin: nil
    build-snaps: [ gnome-42-2204 ]
    override-prime: |
        set -eux
        cd /snap/gnome-42-2204/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;

apps:
  godot-3-5:
    extensions: [gnome]
    command: Godot_v$SNAPCRAFT_PROJECT_VERSION-stable_mono_x11.64
    desktop: meta/gui/godot-3-5.desktop
    plugs:
      - home
      - network
      - audio-playback
      - audio-record
      - removable-media
      - joystick
      - hardware-observe
    environment:
      HOME: $SNAP_USER_COMMON
      VK_ICD_FILENAMESr: /var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json:$SNAP/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:$SNAP/usr/share/vulkan/icd.d/intel_icd.x86_64.json
